export const products = [
  {
    id: 1,
    img: '/images/panwine/rectangle1.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 2,
    img: '/images/panwine/rectangle2.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 3,
    img: '/images/panwine/rectangle3.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 4,
    img: '/images/panwine/rectangle4.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 5,
    img: '/images/panwine/rectangle5.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 6,
    img: '/images/panwine/rectangle.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 7,
    img: '/images/panwine/rectangle7.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 8,
    img: '/images/panwine/rectangle8.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
  {
    id: 9,
    img: '/images/panwine/rectangle.png',
    title: 'Dolceto',
    price: '12,400',
    addToCart: 'Add To Cart',
  },
]
